# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title FPOPDp 
#'                                                                                                        
#' @description Detecting changepoints using the functional pruning optimal partitioning method (fpop) in bivariate time series.                         
#'                                                                                                       
#' @param data is a matrix of data.                               
#' @param penalty is a value of penalty (a non-negative real number).                                        
#' @param type is a value defining the  type of pruning (1 = FPOP(intersection of sets, approximation - rectangle); 2 = FPOP(intersection of set \ union of set, approximation - rectangle); 3 = FPOP(intersection of set \ union of set, approximation -last disk)).       
#'                                                                                                          
#' @return a list of  elements  = (changepoints, means, globalCost).                    
#'  
#' \describe{
#' \item{\code{changepoints}}{is the vector of changepoints.}
#' \item{\code{means}}{is the matrix of successive means for data.}
#' \item{\code{globalCost}}{is a number equal to the global cost.}
#' }                                                                                                                                                                             #     
#' 
#' @examples Data =  data_genDp(p = 3, n = 4, chpts = c(2, 4), means = matrix(c (0, 0, 0, 10, 10, 10), nrow = 3), noise = 1) FPOPDp(Data, penalty = 2*log(4),  type = 3)  FPOPDp(data = matrix(c(0,0,0,0,1,1,2,2,2,2,0,0), nrow = 2), penalty = 2*log(6),  type = 1) 
FPOPDp <- function(data, penalty, type) {
    .Call(`_FPOPapprox2D_FPOPDp`, data, penalty, type)
}

